version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=glns
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=parking
    ports:
      - '5432:5432'
